name: daily-task


on:
  
  #push: # push触发
    #branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '21 0/2 * * *'
    

jobs:
  daily-task:
    if: github.event.repository.owner.id == github.event.sender.id

    env:
      UNICOM_ACCOUNTSN: ${{secrets.unicom_accountSn}} 

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]
        node-registry: ['https://registry.npmjs.org']

    steps:
    
    # 检出
    - name: Checkout
      uses: actions/checkout@v2
      
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ matrix.node-registry }}

    # 安装依赖
    - name: Install dependencies
      run: npm install
      
    - name: Set date time
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"
    
    - name: Set cache time
      id: cdate
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: restore task cache
      uses: actions/cache@v2
      id: use-task-cache
      with:
        path: |
          /home/runner/.AutoSignMachine
        key: ${{ runner.os }}-task-${{ steps.date.outputs.date }}
        restore-keys: |
          ${{ runner.os }}-task-${{ steps.cdate.outputs.date }}
          ${{ runner.os }}-
     
       
    
    # 运行 unicom 签到任务
    - name: Run unicom daily task with no AccountSn
      if: ${{ env.UNICOM_ACCOUNTSN }} == false
      env:
        user: ${{ secrets.unicom_user }}
        password: ${{ secrets.unicom_password }}
        appid: ${{ secrets.unicom_appid }}
      run: node index.js unicom --user=${user} --password=${password} --appid=${appid}  
     # run: node index.js unicom --user=${user} --password=${password} --appid=${appid}  --tryrun --tasks dailygameflow
    - name: Run unicom daily task with Accountsn = 1
      if: ${{ env.UNICOM_ACCOUNTSN == '1' }}
      env:
        accountSn: ${{ secrets.unicom_accountSn }}
        user_1: ${{ secrets.unicom_user }}
        password_1: ${{ secrets.unicom_password }}
        appid_1: ${{ secrets.unicom_appid }}
      run: node index.js unicom --accountSn=${accountSn} --user-1=${user_1} --password-1=${password_1} --appid-1=${appid_1}  
    - name: Run unicom daily task with Accountsn = 1,2
      if: ${{ env.UNICOM_ACCOUNTSN == '1,2' }}
      env:
        accountSn: ${{ secrets.unicom_accountSn }}
        user_1: ${{ secrets.unicom_user }}
        password_1: ${{ secrets.unicom_password }}
        appid_1: ${{ secrets.unicom_appid }}
        user_2: ${{ secrets.unicom_user_2 }}
        password_2: ${{ secrets.unicom_password_2 }}
        appid_2: ${{ secrets.unicom_appid_2 }}
      run: node index.js unicom --accountSn=${accountSn} --user-1=${user_1} --password-1=${password_1} --appid-1=${appid_1} --user-2=${user_2} --password-2=${password_2} --appid-2=${appid_2} 

    - name: Run unicom daily task with Accountsn = 1,2,3
      if: ${{ env.UNICOM_ACCOUNTSN == '1,2,3' }}
      env:
        accountSn: ${{ secrets.unicom_accountSn }}
        user_1: ${{ secrets.unicom_user }}
        password_1: ${{ secrets.unicom_password }}
        appid_1: ${{ secrets.unicom_appid }}
        user_2: ${{ secrets.unicom_user_2 }}
        password_2: ${{ secrets.unicom_password_2 }}
        appid_2: ${{ secrets.unicom_appid_2 }}
        user_3: ${{ secrets.unicom_user_3 }}
        password_3: ${{ secrets.unicom_password_3}}
        appid_3: ${{ secrets.unicom_appid_3 }}
      run: node index.js unicom --accountSn=${accountSn} --user-1=${user_1} --password-1=${password_1} --appid-1=${appid_1} --user-2=${user_2} --password-2=${password_2} --appid-2=${appid_2} --user-3=${user_3} --password-3=${password_3} --appid-3=${appid_3} 
